### ISSUE TITLE
Add support for running multiple instances

### ISSUE THREAD

**Issue by jeffWelling** [hashicorp/vault-load-testing#4]
Hello!

This is an awesome tool, I had it up and running in 5 minutes, thank you kindly for your work on it!

I'd like to request a feature, I wish to be able to run multiple instances of the load test against the same vault server, but because of the way the test secrets are currently created I predict they will end up interfering with each other.

Adding a unique identifier to the secrets that the load test creates would avoid this problem.

**Comment by tradel** [comment]
Closed by PR#8.
